name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: 519888.spec
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: 519888_hexin.spec

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            dist/windows/
            config.json

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/windows/
            config.json
          token: ${{ secrets.GITHUB_TOKEN }}
