name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: 519888.spec
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: 519888_hexin.spec

      - name: move
        run: mv dist/windows/* ./

      - name: zip
        run: zip release.zip *.exe config.json

      - name: md5
        run: md5 release.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
