name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: |
            519888.spec
            519888_hexin.spec

      - uses: actions/upload-artifact@v4
        with:
          path: |
            dist/windows
            config.json
